//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Advertisers struct {
	ID                 int32
	ParentID           *int64
	Source             *int32
	Name               *string
	DisplayName        *string
	Affiliateid        *string
	DeeplinkAdvertiser *string
	Active             *int32
	NotLinkable        *int32
	DuplicateImages    *int32
	LastUpdated        *time.Time
	AdvertiserHomepage *string
	Featured           *int32
	DivisionID         *int64
}
