//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type CampaignSales struct {
	InfluencerID                int64
	BrandID                     string
	AdvertiserID                int64
	CampaignID                  int64
	CollaborationID             int64
	Channel                     string
	GrossSales                  float64
	GrossCommission             float64
	DayEventDatetime            time.Time
	FirstObligationApprovalDate *time.Time
}
