//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Campaigns struct {
	ID                   int64
	BrandID              *string
	AdvertiserID         *int64
	OriginID             int32
	LogoID               *int64
	LogoImageURL         *string
	HeroImageURL         *string
	Title                *string
	Description          *string
	Budget               int64
	TotalBudget          *int64
	CategoriesStyles     *string
	StartDate            time.Time
	EndDate              *time.Time
	AccountConsultant    *string
	AccountManager       *string
	AdditionalGuidelines *string
	ImageryGuidelines    *string
	State                string
	ReportingStartDate   *time.Time
	ReportingEndDate     *time.Time
}
