//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Collaborations struct {
	ID                            int64
	InfluencerID                  int64
	CampaignID                    int64
	AdvertiserID                  int64
	BrandID                       *string
	SuggestedRate                 *int32
	Payment                       int64
	BonusPayment                  int64
	GiftingPayment                int64
	CollaborationStatusID         int32
	AgencyAccountID               *int64
	PaymentStatusID               *int32
	AcceptedByPublisherID         *int64
	MessagingChannelID            *string
	AcceptedCollaborationSnapshot *string
	StartDate                     *time.Time
	EndDate                       *time.Time
	DateCreated                   *time.Time
	DateUpdated                   *time.Time
	DateAccepted                  *time.Time
	DateCompleted                 *time.Time
	DateOffered                   *time.Time
}
