//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Influencers struct {
	ID                 int64
	Name               *string
	ImageURL           *string
	DateCreated        *time.Time
	BlogNameRsAccounts *string
	BlogRsAccounts     *string
	BlogURL            *string
	BlogName           *string
	Facebook           *string
	Instagram          *string
	Pinterest          *string
	Snapchat           *string
	Twitter            *string
	Youtube            *string
	Tiktok             *string
	Ltk                *string
}
