//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Obligations struct {
	ID                         int64
	CampaignID                 int64
	AdvertiserID               *int64
	CollaborationID            *int64
	InfluencerID               *int64
	BrandID                    *string
	PostID                     *string
	ObligationSubmissionURL    *string
	ObligationTypeID           int32
	ObligationSubmissionTypeID int32
	ObligationStatusID         int32
	DateCreated                *time.Time
	DateUpdated                *time.Time
	DateSubmitted              *time.Time
	DateApproved               *time.Time
}
