//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PostMetrics struct {
	PostID         string
	InfluencerID   int64
	ObligationID   int64
	SubmittedURL   string
	Channel        string
	ChannelType    string
	Reach          int32
	Impressions    int32
	Likes          int32
	Comments       int32
	Shares         int32
	Engagements    int32
	EngagementRate float64
}
