//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type SocialFollowers struct {
	InfluencerID       int64
	Channel            *string
	ChannelAccountName *string
	Followers          *int64
	Linked             *bool
}
