//
// Code generated by go-jet DO NOT EDIT.
// Generated at Thursday, 26-Sep-19 12:02:13 CEST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var CustomerList = newCustomerListTable()

type CustomerListTable struct {
	postgres.Table

	//Columns
	ID      postgres.ColumnInteger
	Name    postgres.ColumnString
	Address postgres.ColumnString
	ZipCode postgres.ColumnString
	Phone   postgres.ColumnString
	City    postgres.ColumnString
	Country postgres.ColumnString
	Notes   postgres.ColumnString
	Sid     postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new CustomerListTable with assigned alias
func (a *CustomerListTable) AS(alias string) *CustomerListTable {
	aliasTable := newCustomerListTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newCustomerListTable() *CustomerListTable {
	var (
		IDColumn      = postgres.IntegerColumn("id")
		NameColumn    = postgres.StringColumn("name")
		AddressColumn = postgres.StringColumn("address")
		ZipCodeColumn = postgres.StringColumn("zip code")
		PhoneColumn   = postgres.StringColumn("phone")
		CityColumn    = postgres.StringColumn("city")
		CountryColumn = postgres.StringColumn("country")
		NotesColumn   = postgres.StringColumn("notes")
		SidColumn     = postgres.IntegerColumn("sid")
	)

	return &CustomerListTable{
		Table: postgres.NewTable("dvds", "customer_list", IDColumn, NameColumn, AddressColumn, ZipCodeColumn, PhoneColumn, CityColumn, CountryColumn, NotesColumn, SidColumn),

		//Columns
		ID:      IDColumn,
		Name:    NameColumn,
		Address: AddressColumn,
		ZipCode: ZipCodeColumn,
		Phone:   PhoneColumn,
		City:    CityColumn,
		Country: CountryColumn,
		Notes:   NotesColumn,
		Sid:     SidColumn,

		AllColumns:     postgres.ColumnList{IDColumn, NameColumn, AddressColumn, ZipCodeColumn, PhoneColumn, CityColumn, CountryColumn, NotesColumn, SidColumn},
		MutableColumns: postgres.ColumnList{IDColumn, NameColumn, AddressColumn, ZipCodeColumn, PhoneColumn, CityColumn, CountryColumn, NotesColumn, SidColumn},
	}
}
