//
// Code generated by go-jet DO NOT EDIT.
// Generated at Thursday, 26-Sep-19 12:02:13 CEST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var Category = newCategoryTable()

type CategoryTable struct {
	postgres.Table

	//Columns
	CategoryID postgres.ColumnInteger
	Name       postgres.ColumnString
	LastUpdate postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new CategoryTable with assigned alias
func (a *CategoryTable) AS(alias string) *CategoryTable {
	aliasTable := newCategoryTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newCategoryTable() *CategoryTable {
	var (
		CategoryIDColumn = postgres.IntegerColumn("category_id")
		NameColumn       = postgres.StringColumn("name")
		LastUpdateColumn = postgres.TimestampColumn("last_update")
	)

	return &CategoryTable{
		Table: postgres.NewTable("dvds", "category", CategoryIDColumn, NameColumn, LastUpdateColumn),

		//Columns
		CategoryID: CategoryIDColumn,
		Name:       NameColumn,
		LastUpdate: LastUpdateColumn,

		AllColumns:     postgres.ColumnList{CategoryIDColumn, NameColumn, LastUpdateColumn},
		MutableColumns: postgres.ColumnList{NameColumn, LastUpdateColumn},
	}
}
