//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Language = newLanguageTable("dvds", "language", "")

type languageTable struct {
	postgres.Table

	//Columns
	LanguageID postgres.ColumnInteger
	Name       postgres.ColumnString
	LastUpdate postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type LanguageTable struct {
	languageTable

	EXCLUDED languageTable
}

// AS creates new LanguageTable with assigned alias
func (a LanguageTable) AS(alias string) *LanguageTable {
	return newLanguageTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LanguageTable with assigned schema name
func (a LanguageTable) FromSchema(schemaName string) *LanguageTable {
	return newLanguageTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LanguageTable with assigned table prefix
func (a LanguageTable) WithPrefix(prefix string) *LanguageTable {
	return newLanguageTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LanguageTable with assigned table suffix
func (a LanguageTable) WithSuffix(suffix string) *LanguageTable {
	return newLanguageTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLanguageTable(schemaName, tableName, alias string) *LanguageTable {
	return &LanguageTable{
		languageTable: newLanguageTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newLanguageTableImpl("", "excluded", ""),
	}
}

func newLanguageTableImpl(schemaName, tableName, alias string) languageTable {
	var (
		LanguageIDColumn = postgres.IntegerColumn("language_id")
		NameColumn       = postgres.StringColumn("name")
		LastUpdateColumn = postgres.TimestampColumn("last_update")
		allColumns       = postgres.ColumnList{LanguageIDColumn, NameColumn, LastUpdateColumn}
		mutableColumns   = postgres.ColumnList{NameColumn, LastUpdateColumn}
	)

	return languageTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		LanguageID: LanguageIDColumn,
		Name:       NameColumn,
		LastUpdate: LastUpdateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
