//
// Code generated by go-jet DO NOT EDIT.
// Generated at Wednesday, 17-Jul-19 13:11:01 CEST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet"

var MpaaRating = &struct {
	G    jet.StringExpression
	Pg   jet.StringExpression
	Pg13 jet.StringExpression
	R    jet.StringExpression
	Nc17 jet.StringExpression
}{
	G:    jet.NewEnumValue("G"),
	Pg:   jet.NewEnumValue("PG"),
	Pg13: jet.NewEnumValue("PG-13"),
	R:    jet.NewEnumValue("R"),
	Nc17: jet.NewEnumValue("NC-17"),
}
